# Generated by Django 3.2.23 on 2023-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('monthly_income', models.IntegerField(default=0)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('approved_limit', models.IntegerField(default=0)),
                ('customer_id', models.IntegerField(default=0, unique=True)),
            ],
        ),
    ]
