# Generated by Django 3.2.23 on 2023-12-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231220_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.CharField(max_length=100),
        ),
    ]
