# Generated by Django 3.2.23 on 2023-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231220_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('loan_id', models.CharField(max_length=255)),
                ('loan_amount', models.CharField(max_length=255)),
                ('tenure', models.CharField(max_length=255)),
                ('interest_rate', models.CharField(max_length=255)),
                ('monthly_repayment_emi', models.CharField(max_length=255)),
                ('emis_paid_on_time', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.CharField(max_length=50),
        ),
    ]
