# Generated by Django 3.2.23 on 2023-12-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_loan_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='start_date',
            new_name='approval_date',
        ),
    ]
