# Generated by Django 3.2.23 on 2023-12-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231220_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='userid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
