# Generated by Django 3.2.23 on 2023-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20231221_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approval_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
