# Generated by Django 3.2.23 on 2023-12-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_loan_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
    ]
