# Generated by Django 3.2.23 on 2023-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20231224_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_repayment_emi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
