# Generated by Django 3.2.23 on 2023-12-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20231224_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('tenure', models.IntegerField()),
            ],
        ),
    ]
